import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <main style={{ flex: 1 }}>{children}</main>

        <footer
          style={{
            // backgroundColor: "#111",
            color: "#535353ff",
            textAlign: "center",
            padding: "15px 0",
            fontSize: "14px",
          }}
        >
          © 2025 Lucas Panfieti. Todos os direitos reservados.
        </footer>
      </body>
    </html>
  );
}
